### ISSUE TITLE
Pymongo 3.0 breaking API changes

### ISSUE THREAD

**Issue by tomsteele** [fishnetsecurity/Lair-Drones#15]
```
Traceback (most recent call last):
  File "/usr/local/bin/drone-nessus", line 52, in <module>
    db = api.db_connect()
  File "/Library/Python/2.7/site-packages/lairdrone/api.py", line 29, in db_connect
    from pymongo import Connection, uri_parser
ImportError: cannot import name Connection
```

I think we just need to force the 2.X branch in setup.py. Thank goodness we'll be living that Go lyfe soon :sunglasses:

**Comment by tomsteele** [comment]
Fixed
